/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.Principal.matricula;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan
 */
public class VentanaExtra extends javax.swing.JFrame {

    VentanaElegirCursosAlumno v = new VentanaElegirCursosAlumno();
    /**
     * Creates new form VentanaExtra
     */
    public VentanaExtra() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        cboMusica = new javax.swing.JComboBox<>();
        btnRegistrarExtra = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        cboDeporte = new javax.swing.JComboBox<>();
        cboArte = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cboMusica.setBackground(new java.awt.Color(0, 0, 204));
        cboMusica.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cboMusica.setForeground(new java.awt.Color(255, 255, 255));
        cboMusica.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "GUITARRA", "PIANO", "FLAUTA" }));
        jPanel6.add(cboMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, -1, -1));

        btnRegistrarExtra.setText("REGISTRAR");
        btnRegistrarExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarExtraActionPerformed(evt);
            }
        });
        jPanel6.add(btnRegistrarExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 0, 0));
        jLabel21.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("DEPORTE");
        jLabel21.setOpaque(true);
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 0, 0));
        jLabel20.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("ARTE");
        jLabel20.setOpaque(true);
        jPanel6.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 80, -1));

        jLabel40.setBackground(new java.awt.Color(255, 0, 0));
        jLabel40.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("MUSICA");
        jLabel40.setOpaque(true);
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, -1, -1));

        cboDeporte.setBackground(new java.awt.Color(0, 0, 204));
        cboDeporte.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cboDeporte.setForeground(new java.awt.Color(255, 255, 255));
        cboDeporte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FUTBOL", "NATACION", "ATLETISMO" }));
        jPanel6.add(cboDeporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        cboArte.setBackground(new java.awt.Color(0, 0, 204));
        cboArte.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        cboArte.setForeground(new java.awt.Color(255, 255, 255));
        cboArte.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PINTURA", "DIBUJO", "FOTOGRAFIA", " " }));
        jPanel6.add(cboArte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 0, 0));
        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("CURSOS EXTRACURRICULARES");
        jLabel18.setOpaque(true);
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton12.setText("VOLVER");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarExtraActionPerformed
        // TODO add your handling code here:

        if(cboArte.getSelectedItem().equals("DIBUJO")){
            Arte a = new Arte();
            a.setNombreArte("DIBUJO");
            matricula.alumnos.get(VentanaPrincipal.idesito).setA(a);
        }else if(cboArte.getSelectedItem().equals("PINTURA")){
            Arte a = new Arte();
            a.setNombreArte("PINTURA");
            matricula.alumnos.get(VentanaPrincipal.idesito).setA(a);
        }else if(cboArte.getSelectedItem().equals("FOTOGRAFIA")){
            Arte a = new Arte();
            a.setNombreArte("FOTOGRAFIA");
            matricula.alumnos.get(VentanaPrincipal.idesito).setA(a);
        }
        if(cboDeporte.getSelectedItem().equals("FUTBOL")){
            Deporte d = new Deporte();
            d.setNombreDeporte("FUTBOL");
            matricula.alumnos.get(VentanaPrincipal.idesito).setD(d);

        }else if(cboDeporte.getSelectedItem().equals("NATACION")){
            Deporte d = new Deporte();
            d.setNombreDeporte("NATACION");
            matricula.alumnos.get(VentanaPrincipal.idesito).setD(d);
        }else if(cboDeporte.getSelectedItem().equals("ATLETISMO")){
            Deporte d = new Deporte();
            d.setNombreDeporte("ATLETISMO");
            matricula.alumnos.get(VentanaPrincipal.idesito).setD(d);
        }

        if(cboMusica.getSelectedItem().equals("GUITARRA")){
            Musica m = new Musica();
            m.setNombreMusica("GUITARRA");
            matricula.alumnos.get(VentanaPrincipal.idesito).setM(m);
        }else if(cboMusica.getSelectedItem().equals("PIANO")){
            Musica m = new Musica();
            m.setNombreMusica("GUITARRA");
            matricula.alumnos.get(VentanaPrincipal.idesito).setM(m);
        }else if(cboMusica.getSelectedItem().equals("FLAUTA")){
            Musica m = new Musica();
            m.setNombreMusica("GUITARRA");
            matricula.alumnos.get(VentanaPrincipal.idesito).setM(m);
        }

        JOptionPane.showMessageDialog(null, "Se Registro con exito");
        this.setVisible(false);
        v.setVisible(true);
        v.txtIdAlumnoBuscado.setText("");
        
        v.txtEleccionCurso.setText("");
        v.txtEleccionCurso.setEnabled(false);
        v.btnActividadExtra.setEnabled(false);
        v.btnElegirCurso.setEnabled(false);
    }//GEN-LAST:event_btnRegistrarExtraActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
       v.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaExtra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaExtra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarExtra;
    private javax.swing.JComboBox<String> cboArte;
    private javax.swing.JComboBox<String> cboDeporte;
    private javax.swing.JComboBox<String> cboMusica;
    private javax.swing.JButton jButton12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
