/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.Principal.Menu;
import static clases.Principal.elegircurso;
import static clases.Principal.matricula;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Victor && Harol
 */
public class VentanaPrincipal extends javax.swing.JFrame {
//bebesito
    /**
     * Creates new form VentanaPrincipal
     */
    public Matricula matricula = new Matricula();
    DefaultListModel<String> modeloAlumno = new DefaultListModel<>();
   
    public VentanaPrincipal() {
        initComponents();
        this.setSize(500,500);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setResizable(false);
        this.VentanaAgregarAlumno.setSize(500,500);
        this.VentanaAgregarAlumno.setResizable(false);
        this.VentanaAgregarAlumno.setLocationRelativeTo(null);
        this.VentanaAgregarAlumno.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.VentanaBuscarAlumno.setSize(500,500);
        this.VentanaBuscarAlumno.setResizable(false);
        this.VentanaBuscarAlumno.setLocationRelativeTo(null);
        this.VentanaBuscarAlumno.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.VentanaEliminarAlumno.setSize(500,500);
        this.VentanaEliminarAlumno.setResizable(false);
        this.VentanaEliminarAlumno.setLocationRelativeTo(null);
        this.VentanaEliminarAlumno.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.VentanaModificarDatosAlumno.setSize(500,500);
        this.VentanaModificarDatosAlumno.setResizable(false);
        this.VentanaModificarDatosAlumno.setLocationRelativeTo(null);
        this.VentanaModificarDatosAlumno.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.VentanaMostrarDatosAlumno.setSize(500,500);
        this.VentanaMostrarDatosAlumno.setResizable(false);
        this.VentanaMostrarDatosAlumno.setLocationRelativeTo(null);
        this.VentanaMostrarDatosAlumno.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.VentanaElegirCurso.setSize(500,500);
        this.VentanaElegirCurso.setResizable(false);
        this.VentanaElegirCurso.setLocationRelativeTo(null);
        this.VentanaElegirCurso.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
/*METODOS*/
    public static void elegircurso(Alumno alum){
        
        int opc2;
               
                Curso curso = new Curso();
                curso.elegirCurso();
                alum.agregarCurso(curso);
               
               opc2=Integer.parseInt(JOptionPane.showInputDialog(null,"Desea elegir otro curso: ? \n "+
                       "1. Si \n"+
                       "2. No \n"));
               switch(opc2){
                   case 1: elegircurso(alum);
                            break;
                   case 2:  JOptionPane.showMessageDialog(null, "Elegio no");
                            
                            break;
               }
       
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VentanaAgregarAlumno = new javax.swing.JFrame();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtSexoAlumno = new javax.swing.JTextField();
        txtIdAlumno = new javax.swing.JTextField();
        txtNombreAlumno = new javax.swing.JTextField();
        txtApellidoAlumno = new javax.swing.JTextField();
        txtEdadAlumno = new javax.swing.JTextField();
        btnRegistrarAlumno = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtNombreApoderado = new javax.swing.JTextField();
        txtTelefonoApoderado = new javax.swing.JTextField();
        txtDireccionApoderado = new javax.swing.JTextField();
        txtDniApoderado = new javax.swing.JTextField();
        txtParentescoApoderado = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel25 = new javax.swing.JLabel();
        VentanaBuscarAlumno = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        txtIdAlumnoBuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnBuscarAlumnito = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAlumnoBuscado = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        VentanaMostrarDatosAlumno = new javax.swing.JFrame();
        jPanel7 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        ListaAlumnosRegistrados = new javax.swing.JList<>();
        jButton10 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        VentanaModificarDatosAlumno = new javax.swing.JFrame();
        jButton9 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNombreModificar = new javax.swing.JTextField();
        txtSexoModificar = new javax.swing.JTextField();
        txtIdModificar = new javax.swing.JTextField();
        txtApellidoModificar = new javax.swing.JTextField();
        txtEdadModificar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txtIdBuscarModificar = new javax.swing.JTextField();
        btnBuscarModificar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        VentanaEliminarAlumno = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton13 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaAlumnosDos = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        txtAlumnoEliminar = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        VentanaElegirCurso = new javax.swing.JFrame();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdAlumnoBuscado = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCursos = new javax.swing.JTextArea();
        txtEleccionCurso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnElegirCurso = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        VentanaAgregarAlumno.setResizable(false);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(255, 0, 0));
        jButton6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("VOLVER");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, -1, -1));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("AGREGAR ALUMNO");
        jLabel6.setOpaque(true);
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel7.setText("EDAD:");
        jLabel7.setOpaque(true);
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel8.setText("NOMBRE:");
        jLabel8.setOpaque(true);
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel9.setText("APELLIDO:");
        jLabel9.setOpaque(true);
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setText("SEXO:");
        jLabel10.setOpaque(true);
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel11.setText("ID:");
        jLabel11.setOpaque(true);
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));
        jPanel4.add(txtSexoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 210, -1));

        txtIdAlumno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdAlumnoMouseClicked(evt);
            }
        });
        txtIdAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlumnoActionPerformed(evt);
            }
        });
        jPanel4.add(txtIdAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 210, -1));
        jPanel4.add(txtNombreAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 210, -1));

        txtApellidoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoAlumnoActionPerformed(evt);
            }
        });
        jPanel4.add(txtApellidoAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 210, -1));
        jPanel4.add(txtEdadAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 210, -1));

        btnRegistrarAlumno.setBackground(new java.awt.Color(255, 0, 0));
        btnRegistrarAlumno.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnRegistrarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarAlumno.setText("REGISTRAR");
        btnRegistrarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarAlumnoActionPerformed(evt);
            }
        });
        jPanel4.add(btnRegistrarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 90, -1));

        jLabel31.setBackground(new java.awt.Color(255, 0, 0));
        jLabel31.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel31.setText("Parentesco:");
        jLabel31.setOpaque(true);
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, -1));

        jLabel32.setBackground(new java.awt.Color(255, 0, 0));
        jLabel32.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel32.setText("Nombre: ");
        jLabel32.setOpaque(true);
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel33.setBackground(new java.awt.Color(255, 0, 0));
        jLabel33.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel33.setText("Direccion:");
        jLabel33.setOpaque(true);
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel34.setBackground(new java.awt.Color(255, 0, 0));
        jLabel34.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel34.setText("Telefono:");
        jLabel34.setOpaque(true);
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel35.setBackground(new java.awt.Color(255, 0, 0));
        jLabel35.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel35.setText("DNI:");
        jLabel35.setOpaque(true);
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        txtNombreApoderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreApoderadoActionPerformed(evt);
            }
        });
        jPanel4.add(txtNombreApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 210, -1));
        jPanel4.add(txtTelefonoApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 210, -1));
        jPanel4.add(txtDireccionApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 210, -1));
        jPanel4.add(txtDniApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 210, -1));
        jPanel4.add(txtParentescoApoderado, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 210, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 500, 20));

        jLabel25.setBackground(new java.awt.Color(255, 0, 0));
        jLabel25.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout VentanaAgregarAlumnoLayout = new javax.swing.GroupLayout(VentanaAgregarAlumno.getContentPane());
        VentanaAgregarAlumno.getContentPane().setLayout(VentanaAgregarAlumnoLayout);
        VentanaAgregarAlumnoLayout.setHorizontalGroup(
            VentanaAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaAgregarAlumnoLayout.setVerticalGroup(
            VentanaAgregarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR ALUMNO");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, -1, -1));

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("VOLVER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));
        jPanel1.add(txtIdAlumnoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, -1));

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("INGRESA ID:");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btnBuscarAlumnito.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscarAlumnito.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuscarAlumnito.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumnito.setText("BUSCAR ALUMNO");
        btnBuscarAlumnito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnitoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAlumnito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        txtAreaAlumnoBuscado.setEditable(false);
        txtAreaAlumnoBuscado.setColumns(20);
        txtAreaAlumnoBuscado.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtAreaAlumnoBuscado.setRows(5);
        txtAreaAlumnoBuscado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Alumno Buscado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane3.setViewportView(txtAreaAlumnoBuscado);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 370, 110));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout VentanaBuscarAlumnoLayout = new javax.swing.GroupLayout(VentanaBuscarAlumno.getContentPane());
        VentanaBuscarAlumno.getContentPane().setLayout(VentanaBuscarAlumnoLayout);
        VentanaBuscarAlumnoLayout.setHorizontalGroup(
            VentanaBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaBuscarAlumnoLayout.setVerticalGroup(
            VentanaBuscarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setBackground(new java.awt.Color(255, 0, 0));
        jLabel23.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("MOSTRAR ALUMNOS REGISTRADOS");
        jLabel23.setOpaque(true);
        jPanel7.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 8, -1, 30));

        ListaAlumnosRegistrados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE ALUMNOS REGISTRADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane5.setViewportView(ListaAlumnosRegistrados);

        jPanel7.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 440, 360));

        jButton10.setBackground(new java.awt.Color(255, 0, 0));
        jButton10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("VOLVER");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel7.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout VentanaMostrarDatosAlumnoLayout = new javax.swing.GroupLayout(VentanaMostrarDatosAlumno.getContentPane());
        VentanaMostrarDatosAlumno.getContentPane().setLayout(VentanaMostrarDatosAlumnoLayout);
        VentanaMostrarDatosAlumnoLayout.setHorizontalGroup(
            VentanaMostrarDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaMostrarDatosAlumnoLayout.setVerticalGroup(
            VentanaMostrarDatosAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        VentanaModificarDatosAlumno.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton9.setBackground(new java.awt.Color(255, 0, 0));
        jButton9.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("VOLVER");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, -1, -1));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MODIFICAR DATOS DE ALUMNO");
        jLabel4.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        txtNombreModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreModificarActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(txtNombreModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, -1));
        VentanaModificarDatosAlumno.getContentPane().add(txtSexoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 170, -1));

        txtIdModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdModificarActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(txtIdModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 170, -1));

        txtApellidoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoModificarActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(txtApellidoModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 170, -1));
        VentanaModificarDatosAlumno.getContentPane().add(txtEdadModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 170, -1));

        jLabel22.setBackground(new java.awt.Color(255, 0, 0));
        jLabel22.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Edad:");
        jLabel22.setToolTipText("");
        jLabel22.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        VentanaModificarDatosAlumno.getContentPane().add(txtIdBuscarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        btnBuscarModificar.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscarModificar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuscarModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarModificar.setText("BUSCAR");
        btnBuscarModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarModificarActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(btnBuscarModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        btnActualizar.setBackground(new java.awt.Color(255, 0, 0));
        btnActualizar.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("ACTUALIZAR");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        VentanaModificarDatosAlumno.getContentPane().add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jLabel30.setBackground(new java.awt.Color(255, 0, 0));
        jLabel30.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("INGRESA ID:");
        jLabel30.setToolTipText("");
        jLabel30.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, -1));

        jLabel36.setBackground(new java.awt.Color(255, 0, 0));
        jLabel36.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("ID:");
        jLabel36.setToolTipText("");
        jLabel36.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));

        jLabel37.setBackground(new java.awt.Color(255, 0, 0));
        jLabel37.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Nombre:");
        jLabel37.setToolTipText("");
        jLabel37.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, -1));

        jLabel38.setBackground(new java.awt.Color(255, 0, 0));
        jLabel38.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Apellido:");
        jLabel38.setToolTipText("");
        jLabel38.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel39.setBackground(new java.awt.Color(255, 0, 0));
        jLabel39.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Sexo:");
        jLabel39.setToolTipText("");
        jLabel39.setOpaque(true);
        VentanaModificarDatosAlumno.getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, -1));

        jLabel28.setBackground(new java.awt.Color(255, 0, 0));
        jLabel28.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        VentanaModificarDatosAlumno.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ELIMINAR ALUMNO");
        jLabel5.setOpaque(true);
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        jButton13.setBackground(new java.awt.Color(255, 0, 0));
        jButton13.setForeground(new java.awt.Color(255, 255, 255));
        jButton13.setText("VOLVER");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, -1, -1));

        listaAlumnosDos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE ALUMNOS REGISTRADOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N
        listaAlumnosDos.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jScrollPane4.setViewportView(listaAlumnosDos);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 400, 160));

        jLabel16.setBackground(new java.awt.Color(255, 0, 0));
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ELEGIR ALUMNO:");
        jLabel16.setOpaque(true);
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));
        jPanel2.add(txtAlumnoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 30));

        jButton7.setBackground(new java.awt.Color(255, 0, 0));
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("ELIMINAR ALUMNO");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout VentanaEliminarAlumnoLayout = new javax.swing.GroupLayout(VentanaEliminarAlumno.getContentPane());
        VentanaEliminarAlumno.getContentPane().setLayout(VentanaEliminarAlumnoLayout);
        VentanaEliminarAlumnoLayout.setHorizontalGroup(
            VentanaEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaEliminarAlumnoLayout.setVerticalGroup(
            VentanaEliminarAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ELEGIR CURSOS");
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 23, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IDALUMNO:");
        jLabel13.setOpaque(true);
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 60, -1, -1));

        txtIdAlumnoBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlumnoBuscadoActionPerformed(evt);
            }
        });
        jPanel5.add(txtIdAlumnoBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 57, 254, -1));

        btnBuscarAlumno.setBackground(new java.awt.Color(255, 51, 0));
        btnBuscarAlumno.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuscarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 88, -1, -1));

        txtAreaCursos.setEditable(false);
        txtAreaCursos.setColumns(20);
        txtAreaCursos.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtAreaCursos.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaCursos.setRows(5);
        txtAreaCursos.setText("\"Cursos: \"\n1. Matematica   Horario:  \t\t- Lunes   7:00-9:00am \n\t                    \t\t- Martes 7:00-9:00am \n                                           \t\t- Jueves 9:00-11:00am\n2. Comunicacion Horario:  \t\t- Lunes  9:00-11:00am \n\t                      \t\t- Miercoles 7:00-11:00\n3. CTA          Horario: \t\t- Martes 9:00-1:00pm \n\t             \t\t- Jueves 11:00-1:00pm\n4. Ingles       Horario: \t\t- Lunes  11:00-1:00pm \n\t             \t\t- Lunes  11:00-1:00pm\n5. Religion     Horario: \t\t- Jueves  7:00-9:00am \n\t               \t\t- Viernes 7:00-9:00am  \n\"6. Psicologia   Horario: \t\t- Viernes 9:00-1:00pm");
        txtAreaCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE CURSOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        txtAreaCursos.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaCursos);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 390, 250));

        txtEleccionCurso.setEnabled(false);
        txtEleccionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEleccionCursoActionPerformed(evt);
            }
        });
        jPanel5.add(txtEleccionCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 379, 194, -1));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ELEGIR CURSO:");
        jLabel14.setOpaque(true);
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 382, -1, -1));

        btnElegirCurso.setBackground(new java.awt.Color(255, 51, 0));
        btnElegirCurso.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnElegirCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnElegirCurso.setText("ELEGIR ");
        btnElegirCurso.setEnabled(false);
        btnElegirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirCursoActionPerformed(evt);
            }
        });
        jPanel5.add(btnElegirCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 378, -1, -1));

        jButton16.setBackground(new java.awt.Color(255, 0, 0));
        jButton16.setForeground(new java.awt.Color(255, 255, 255));
        jButton16.setText("VOLVER");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 412, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        javax.swing.GroupLayout VentanaElegirCursoLayout = new javax.swing.GroupLayout(VentanaElegirCurso.getContentPane());
        VentanaElegirCurso.getContentPane().setLayout(VentanaElegirCursoLayout);
        VentanaElegirCursoLayout.setHorizontalGroup(
            VentanaElegirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        VentanaElegirCursoLayout.setVerticalGroup(
            VentanaElegirCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROCESO DE MATRICULA");
        jLabel1.setOpaque(true);
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 310, -1));

        jButton15.setBackground(new java.awt.Color(255, 0, 0));
        jButton15.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton15.setForeground(new java.awt.Color(255, 255, 255));
        jButton15.setText("ELEGIR CURSOS ALUMNO");
        jButton15.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 260, 30));

        jButton4.setBackground(new java.awt.Color(255, 0, 0));
        jButton4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("MOSTRAR DATOS DEL ALUMNO");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 260, 30));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("AGREGAR ALUMNO");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 260, 30));

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("BUSCAR ALUMNO");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 260, 30));

        jButton5.setBackground(new java.awt.Color(255, 0, 0));
        jButton5.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("ELIMINAR ALUMNO");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 260, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("MODIFICAR DATOS DEL ALUMNO");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, 260, 30));

        jButton11.setBackground(new java.awt.Color(255, 0, 0));
        jButton11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("SALIR");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(255, 255, 255), null, null));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, -1, -1));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.VentanaAgregarAlumno.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.setVisible(rootPaneCheckingEnabled);
        this.VentanaAgregarAlumno.setVisible(false);
       
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.VentanaBuscarAlumno.setVisible(rootPaneCheckingEnabled);
        this.txtIdAlumnoBuscar.setText("");
        this.txtAreaAlumnoBuscado.setText("");
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.VentanaBuscarAlumno.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.VentanaMostrarDatosAlumno.setVisible(rootPaneCheckingEnabled);
        ListaAlumnosRegistrados.removeAll();
        listaAlumnosDos.removeAll();
        
        modeloAlumno.removeAllElements();
        for (int i= 0;i<matricula.alumnos.size();i++){
            modeloAlumno.addElement("Id: "+matricula.alumnos.get(i).getIdAlumno()+"||Nombre: "+matricula.alumnos.get(i).getNombre()+
                    "||Apellido: "+matricula.alumnos.get(i).getApellido()+
                    "||Sexo: "+matricula.alumnos.get(i).getSexo()+
                    "||Edad: "+matricula.alumnos.get(i).getEdad());
            
        }
        listaAlumnosDos.setModel(modeloAlumno);
        ListaAlumnosRegistrados.setModel(modeloAlumno);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.VentanaEliminarAlumno.setVisible(true);
        txtAlumnoEliminar.setText("");
        ListaAlumnosRegistrados.removeAll();
        listaAlumnosDos.removeAll();
        
        modeloAlumno.removeAllElements();
        for (int i= 0;i<matricula.alumnos.size();i++){
            modeloAlumno.addElement("Id: "+matricula.alumnos.get(i).getIdAlumno()+"||Nombre: "+matricula.alumnos.get(i).getNombre()+
                    "||Apellido: "+matricula.alumnos.get(i).getApellido()+
                    "||Sexo: "+matricula.alumnos.get(i).getSexo()+
                    "||Edad: "+matricula.alumnos.get(i).getEdad());
            
        }
        listaAlumnosDos.setModel(modeloAlumno);
        ListaAlumnosRegistrados.setModel(modeloAlumno);
        
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.btnActualizar.setEnabled(false);
        this.VentanaModificarDatosAlumno.setVisible(true);//este metodo hace visible la ventana siguiente
        this.txtIdBuscarModificar.setText("");
        this.txtNombreModificar.setText("");
        this.txtEdadModificar.setText("");
        this.txtApellidoModificar.setText("");
        this.txtSexoModificar.setText("");
        this.txtIdModificar.setText("");
        this.btnActualizar.setEnabled(false);
        dispose();//este metodo lo que hace es desaparecer la ventana anterior
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.VentanaEliminarAlumno.setVisible(false);
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.VentanaModificarDatosAlumno.setVisible(false);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txtIdAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlumnoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtIdAlumnoActionPerformed

    private void txtApellidoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoAlumnoActionPerformed

    private void btnRegistrarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarAlumnoActionPerformed
        
        Alumno alum = new Alumno();
        //Contenedores de Alumno
        String id,nombre,apellido,sexo;
        int edad;
        
        //Contenedores de Apoderado
        String nombreApoderado,telefono,direccion,dni,parentesco;
        //txt's de cajas de Alumno
        id = txtIdAlumno.getText();
        nombre=txtNombreAlumno.getText();
        apellido=txtApellidoAlumno.getText();
        sexo=txtSexoAlumno.getText();
        edad=Integer.parseInt(txtEdadAlumno.getText());
        //txt's de cajas de apoderado
        
        nombreApoderado = txtNombreApoderado.getText();
        telefono = txtTelefonoApoderado.getText();
        direccion = txtDireccionApoderado.getText();
        dni = txtDireccionApoderado.getText();
        parentesco = txtParentescoApoderado.getText();
         alum.setApellido(apellido);
         alum.setEdad(edad);
         alum.setIdAlumno(id);
         alum.setSexo(sexo);
         alum.setNombre(nombre);
         
        
         alum.setApoderado(new Apoderado(nombreApoderado, direccion, telefono, dni, parentesco, alum));
         
         matricula.alumnos.add(alum);
         modeloAlumno.addElement("El Id del alumno : "+alum.getIdAlumno()+">>Nombre: "+alum.getNombre()+">>"+"Apellido: "+alum.getApellido()+">>"+"Sexo: "+alum.getSexo()+">>"+"Edad: "+alum.getEdad());
         //listaAlumnos.setModel(modeloAlumno);
         //listaAlumnosDos.setModel(modeloAlumno);
         //ListaAlumnosRegistrados.setModel(modeloAlumno);
         JOptionPane.showMessageDialog(null, "Se registro con exito");
         txtApellidoAlumno.setText("");
         txtNombreAlumno.setText("");
         txtEdadAlumno.setText("");
         txtSexoAlumno.setText("");
         txtIdAlumno.setText("");
         
         txtTelefonoApoderado.setText("");
         txtDireccionApoderado.setText("");
         txtParentescoApoderado.setText("");
         txtNombreApoderado.setText("");
         txtDniApoderado.setText("");
        
    }//GEN-LAST:event_btnRegistrarAlumnoActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        this.txtEleccionCurso.setText("");
        txtIdAlumnoBuscado.setText("");
        this.VentanaElegirCurso.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton15ActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        String id;
        id = txtIdAlumnoBuscado.getText();
        int indice;
         indice=matricula.BuscarAlumno(id);
         if(indice==-1){
             JOptionPane.showMessageDialog(null,"No se encontro al alumno");
             txtAreaCursos.setEnabled(false);
             txtEleccionCurso.setEnabled(false);
             btnElegirCurso.setEnabled(false);
         }else{
             JOptionPane.showMessageDialog(null, "Se encontro al alumno");
             txtEleccionCurso.setEnabled(true);
             txtAreaCursos.setEnabled(true);
             btnElegirCurso.setEnabled(true);
             
         }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnElegirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirCursoActionPerformed
        // TODO add your handling code here:
        int i;
        i = Integer.parseInt(txtEleccionCurso.getText());
        String id;
        id = txtIdAlumnoBuscado.getText();
        int indice;
         indice=matricula.BuscarAlumno(id);
         if(indice==-1){
             JOptionPane.showMessageDialog(null,"No se encontro al alumno");
             txtAreaCursos.setEnabled(false);
         }else{
             
             txtAreaCursos.setEnabled(true);
             if(matricula.alumnos.get(indice).cursos.size()==6){
                 JOptionPane.showMessageDialog(null, "No puedes registrar mas Cursos");
             }else{
                 if (i == 1) {
                     Curso c = new Curso();
                     c.setNombreCurso("Matematica");
                     String[] diasMate = {"Lunes", "Martes", "Jueves"};
                     String[] horarioMate = {"7:00-9:00am", "9:00-11:00am", "9:00-11:00am"};
                     c.setDias(diasMate);
                     c.setHorario(horarioMate);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso Matematica");
                     txtEleccionCurso.setText("");
                 } else if (i == 2) {
                     Curso c = new Curso();
                     c.setNombreCurso("Comunicacion");
                     String[] diasComunicacion = {"Lunes", "Miercoles"};
                     String[] horarioComunicacion = {"9:00-11:00am", "7:00-11:00am"};
                     c.setDias(diasComunicacion);
                     c.setHorario(horarioComunicacion);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso Comunicacion");
                     txtEleccionCurso.setText("");
                 } else if (i == 3) {
                     Curso c = new Curso();
                     c.setNombreCurso("CTA");
                     String[] diasCta = {"Martes", "Jueves"};
                     String[] horarioCta = {"9:00-1:00pm", "11:00-1:00pm"};
                     c.setDias(diasCta);
                     c.setHorario(horarioCta);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso CTA");
                     txtEleccionCurso.setText("");
                 } else if (i == 4) {
                     Curso c = new Curso();
                     c.setNombreCurso("Ingles");
                     String[] diasIngles = {"Lunes", "Lunes"};
                     String[] horarioIngles = {"11:00-1:00pm", "11:00-1:00pm"};
                     c.setDias(diasIngles);
                     c.setHorario(horarioIngles);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso Ingles");
                     txtEleccionCurso.setText("");

                 }else if(i==5){
                     Curso c = new Curso();
                     c.setNombreCurso("Religion");
                     String[] diasReligion = {"Jueves", "Viernes"};
                     String[] horarioReligion = {"7:00-9:00am", "7:00-9:00am"};
                     c.setDias(diasReligion);
                     c.setHorario(horarioReligion);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso Religion");
                     txtEleccionCurso.setText("");
                 }else if(i==6){
                     Curso c = new Curso();
                     c.setNombreCurso("Psicologia");
                     String[] diasPsico = {"Viernes"};
                     String[] horarioPsico = {"9:00-1:00pm"};
                     c.setDias(diasPsico);
                     c.setHorario(horarioPsico);
                     matricula.alumnos.get(indice).agregarCurso(c);
                     JOptionPane.showMessageDialog(null, "Se registro Curso Psicologia");
                     txtEleccionCurso.setText("");
                 }else if(i!=1 || i!=2 || i!=3 || i!=4 || i!=5 || i!=6){
                     JOptionPane.showMessageDialog(null, "No existe el curso ASI COMO ELLA EN TU VIDA :V ");
                 }
             
             
             
            }
        
         }
    }//GEN-LAST:event_btnElegirCursoActionPerformed

    private void txtEleccionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEleccionCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEleccionCursoActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
       
        this.setVisible(true);
        this.VentanaElegirCurso.setVisible(false);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void btnBuscarAlumnitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnitoActionPerformed
        // TODO add your handling code here:
        String idAlumno;
        int indice;
        idAlumno = txtIdAlumnoBuscar.getText();
        indice=matricula.BuscarAlumno(idAlumno);
        if(indice==-1){
            txtAreaAlumnoBuscado.setText("");
        }else{
            txtAreaAlumnoBuscado.setText("Datos del ALumno:"+
               "\nNombre: "+matricula.alumnos.get(indice).getNombre()+"\n"+
               "Apellido: "+matricula.alumnos.get(indice).getApellido()+"\n"+
               "Edad: "+matricula.alumnos.get(indice).getEdad()+"\n"+
               "Id: "+matricula.alumnos.get(indice).getIdAlumno()+"\n"+
               "Sexo: "+matricula.alumnos.get(indice).getSexo()+"\n"+
                "Datos Del Apoderado"+"\n"+
                "NombreApoderado: "+matricula.alumnos.get(indice).getApoderado().getNombre()+"\n"+
                "DNI: "+matricula.alumnos.get(indice).getApoderado().getDni()+"\n"+
                    "Parentesco: "+matricula.alumnos.get(indice).getApoderado().getParentesco()+"\n"+
                    "Telefono: "+matricula.alumnos.get(indice).getApoderado().getTelefono()+"\n"+
                    "Direccion: "+matricula.alumnos.get(indice).getApoderado().getDireccion()+"\n");
        }
       
    }//GEN-LAST:event_btnBuscarAlumnitoActionPerformed

    private void txtIdAlumnoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlumnoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAlumnoBuscadoActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String id;
        int indice;
        id = txtAlumnoEliminar.getText();
        indice = matricula.BuscarAlumno(id);
        if(indice==-1){
            
        }else{
            
            JOptionPane.showMessageDialog(null, "Se elimino Alumno "+matricula.alumnos.get(indice).getNombre()+" con exito");
            matricula.alumnos.remove(indice);
            
            ListaAlumnosRegistrados.removeAll();
        listaAlumnosDos.removeAll();
        
        modeloAlumno.removeAllElements();
        for (int i= 0;i<matricula.alumnos.size();i++){
            modeloAlumno.addElement("Id: "+matricula.alumnos.get(i).getIdAlumno()+"||Nombre: "+matricula.alumnos.get(i).getNombre()+
                    "||Apellido: "+matricula.alumnos.get(i).getApellido()+
                    "||Sexo: "+matricula.alumnos.get(i).getSexo()+
                    "||Edad: "+matricula.alumnos.get(i).getEdad());
            
        }
        listaAlumnosDos.setModel(modeloAlumno);
        ListaAlumnosRegistrados.setModel(modeloAlumno);
           
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtNombreModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreModificarActionPerformed

    private void txtApellidoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoModificarActionPerformed

    private void btnBuscarModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarModificarActionPerformed
        // TODO add your handling code here:
        String id;
        id = txtIdBuscarModificar.getText();
        int indice=matricula.BuscarAlumno(id);
        if(indice==-1){
            txtApellidoModificar.setEnabled(false);
            txtNombreModificar.setEnabled(false);
            txtEdadModificar.setEnabled(false);
            txtIdModificar.setEnabled(false);
            txtSexoModificar.setEnabled(false);
            
            txtApellidoModificar.setText("NO EXISTE ESE ID");
            txtNombreModificar.setText("NO EXISTE ESE ID");
            txtEdadModificar.setText("NO EXISTE ESE ID");
            txtIdModificar.setText("NO EXISTE ESE ID");
            txtSexoModificar.setText("NO EXISTE ESE ID");
            
            btnActualizar.setEnabled(false);
        }else{
            btnActualizar.setEnabled(true);
            txtApellidoModificar.setEnabled(true);
            txtNombreModificar.setEnabled(true);
            txtEdadModificar.setEnabled(true);
            txtIdModificar.setEnabled(false);
            txtSexoModificar.setEnabled(true);
            
            txtApellidoModificar.setText(matricula.alumnos.get(indice).getApellido());
            txtNombreModificar.setText(matricula.alumnos.get(indice).getNombre());
            txtSexoModificar.setText(matricula.alumnos.get(indice).getSexo());
            txtIdModificar.setText(matricula.alumnos.get(indice).getIdAlumno());
            txtEdadModificar.setText(String.valueOf(matricula.alumnos.get(indice).getEdad()));
        }
       
    }//GEN-LAST:event_btnBuscarModificarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String nombre,apellido,sexo,id;
        int edad;
        int indice;
        nombre = txtNombreModificar.getText();
        apellido = txtApellidoModificar.getText();
        sexo = txtSexoModificar.getText();
        id = txtIdModificar.getText();
        edad = Integer.parseInt(txtEdadModificar.getText());
        indice = matricula.BuscarAlumno(id);
        matricula.alumnos.get(indice).setNombre(nombre);
        matricula.alumnos.get(indice).setApellido(apellido);
        matricula.alumnos.get(indice).setEdad(edad);
        matricula.alumnos.get(indice).setSexo(sexo);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.setVisible(true);
        this.VentanaMostrarDatosAlumno.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void txtIdAlumnoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdAlumnoMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtIdAlumnoMouseClicked

    private void txtIdModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdModificarActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
       System.exit(0);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtNombreApoderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreApoderadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreApoderadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListaAlumnosRegistrados;
    private javax.swing.JFrame VentanaAgregarAlumno;
    private javax.swing.JFrame VentanaBuscarAlumno;
    private javax.swing.JFrame VentanaElegirCurso;
    private javax.swing.JFrame VentanaEliminarAlumno;
    private javax.swing.JFrame VentanaModificarDatosAlumno;
    private javax.swing.JFrame VentanaMostrarDatosAlumno;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscarAlumnito;
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnBuscarModificar;
    private javax.swing.JButton btnElegirCurso;
    private javax.swing.JButton btnRegistrarAlumno;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> listaAlumnosDos;
    private javax.swing.JTextField txtAlumnoEliminar;
    private javax.swing.JTextField txtApellidoAlumno;
    private javax.swing.JTextField txtApellidoModificar;
    private javax.swing.JTextArea txtAreaAlumnoBuscado;
    private javax.swing.JTextArea txtAreaCursos;
    private javax.swing.JTextField txtDireccionApoderado;
    private javax.swing.JTextField txtDniApoderado;
    private javax.swing.JTextField txtEdadAlumno;
    private javax.swing.JTextField txtEdadModificar;
    private javax.swing.JTextField txtEleccionCurso;
    private javax.swing.JTextField txtIdAlumno;
    private javax.swing.JTextField txtIdAlumnoBuscado;
    private javax.swing.JTextField txtIdAlumnoBuscar;
    private javax.swing.JTextField txtIdBuscarModificar;
    private javax.swing.JTextField txtIdModificar;
    private javax.swing.JTextField txtNombreAlumno;
    private javax.swing.JTextField txtNombreApoderado;
    private javax.swing.JTextField txtNombreModificar;
    private javax.swing.JTextField txtParentescoApoderado;
    private javax.swing.JTextField txtSexoAlumno;
    private javax.swing.JTextField txtSexoModificar;
    private javax.swing.JTextField txtTelefonoApoderado;
    // End of variables declaration//GEN-END:variables
}
