/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.Principal.matricula;

/**
 *
 * @author Brayan
 */
public class VentanaBuscarAlumno extends javax.swing.JFrame {

    VentanaPrincipall v ;
    /**
     * Creates new form BuscarAlumno
     */
    public VentanaBuscarAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtIdAlumnoBuscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        btnBuscarAlumnito = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaAlumnoBuscado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BUSCAR ALUMNO");
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, -1, -1));
        jPanel1.add(txtIdAlumnoBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 240, -1));

        jLabel15.setBackground(new java.awt.Color(255, 0, 0));
        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("INGRESA ID:");
        jLabel15.setOpaque(true);
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        btnBuscarAlumnito.setBackground(new java.awt.Color(255, 0, 0));
        btnBuscarAlumnito.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuscarAlumnito.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumnito.setText("BUSCAR ALUMNO");
        btnBuscarAlumnito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnitoActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscarAlumnito, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        txtAreaAlumnoBuscado.setEditable(false);
        txtAreaAlumnoBuscado.setColumns(20);
        txtAreaAlumnoBuscado.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        txtAreaAlumnoBuscado.setRows(5);
        txtAreaAlumnoBuscado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Alumno Buscado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        jScrollPane3.setViewportView(txtAreaAlumnoBuscado);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 370, 110));

        jButton1.setText("VOLVEr");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v = new VentanaPrincipall();
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnBuscarAlumnitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnitoActionPerformed
        // TODO add your handling code here:
        String idAlumno;
        int indice;
        idAlumno = txtIdAlumnoBuscar.getText();
        indice=matricula.BuscarAlumno(idAlumno);
        if(indice==-1){
            txtAreaAlumnoBuscado.setText("");
        }else{
            txtAreaAlumnoBuscado.setText("Datos del ALumno:"+
                "\nNombre: "+matricula.alumnos.get(indice).getNombre()+"\n"+
                "Apellido: "+matricula.alumnos.get(indice).getApellido()+"\n"+
                "Edad: "+matricula.alumnos.get(indice).getEdad()+"\n"+
                "Id: "+matricula.alumnos.get(indice).getIdAlumno()+"\n"+
                "Sexo: "+matricula.alumnos.get(indice).getSexo()+"\n"+
                "Datos Del Apoderado"+"\n"+
                "NombreApoderado: "+matricula.alumnos.get(indice).getApoderado().getNombre()+"\n"+
                "DNI: "+matricula.alumnos.get(indice).getApoderado().getDni()+"\n"+
                "Parentesco: "+matricula.alumnos.get(indice).getApoderado().getParentesco()+"\n"+
                "Telefono: "+matricula.alumnos.get(indice).getApoderado().getTelefono()+"\n"+
                "Direccion: "+matricula.alumnos.get(indice).getApoderado().getDireccion()+"\n");
        }

    }//GEN-LAST:event_btnBuscarAlumnitoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaBuscarAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaBuscarAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumnito;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea txtAreaAlumnoBuscado;
    private javax.swing.JTextField txtIdAlumnoBuscar;
    // End of variables declaration//GEN-END:variables
}
