/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import static clases.Principal.matricula;
import javax.swing.JOptionPane;

/**
 *
 * @author Brayan
 */
public class VentanaElegirCursosAlumno extends javax.swing.JFrame {

    VentanaPrincipall v ;
    VentanaExtra ex;
    /**
     * Creates new form VentanaElegirDatosAlumno
     */
    public VentanaElegirCursosAlumno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtIdAlumnoBuscado = new javax.swing.JTextField();
        btnBuscarAlumno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaCursos = new javax.swing.JTextArea();
        txtEleccionCurso = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnElegirCurso = new javax.swing.JButton();
        btnActividadExtra = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ELEGIR CURSOS");
        jLabel12.setOpaque(true);
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 23, -1, -1));

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("IDALUMNO:");
        jLabel13.setOpaque(true);
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 60, -1, -1));

        txtIdAlumnoBuscado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdAlumnoBuscadoActionPerformed(evt);
            }
        });
        jPanel5.add(txtIdAlumnoBuscado, new org.netbeans.lib.awtextra.AbsoluteConstraints(104, 57, 254, -1));

        btnBuscarAlumno.setBackground(new java.awt.Color(255, 51, 0));
        btnBuscarAlumno.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnBuscarAlumno.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarAlumno.setText("BUSCAR");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });
        jPanel5.add(btnBuscarAlumno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 88, -1, -1));

        txtAreaCursos.setEditable(false);
        txtAreaCursos.setColumns(20);
        txtAreaCursos.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        txtAreaCursos.setForeground(new java.awt.Color(255, 0, 0));
        txtAreaCursos.setRows(5);
        txtAreaCursos.setText("\"Cursos: \"\n1. Matematica   Horario:  \t\t- Lunes   7:00-9:00am \n\t                    \t\t- Martes 7:00-9:00am \n                                           \t\t- Jueves 9:00-11:00am\n2. Comunicacion Horario:  \t\t- Lunes  9:00-11:00am \n\t                      \t\t- Miercoles 7:00-11:00\n3. CTA          Horario: \t\t- Martes 9:00-1:00pm \n\t             \t\t- Jueves 11:00-1:00pm\n4. Ingles       Horario: \t\t- Lunes  11:00-1:00pm \n\t             \t\t- Lunes  11:00-1:00pm\n5. Religion     Horario: \t\t- Jueves  7:00-9:00am \n\t               \t\t- Viernes 7:00-9:00am  \n\"6. Psicologia   Horario: \t\t- Viernes 9:00-1:00pm");
        txtAreaCursos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTA DE CURSOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 3, 14), new java.awt.Color(255, 0, 0))); // NOI18N
        txtAreaCursos.setEnabled(false);
        jScrollPane1.setViewportView(txtAreaCursos);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 390, 250));

        txtEleccionCurso.setEnabled(false);
        txtEleccionCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEleccionCursoActionPerformed(evt);
            }
        });
        jPanel5.add(txtEleccionCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 379, 194, -1));

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ELEGIR CURSO:");
        jLabel14.setOpaque(true);
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 382, -1, -1));

        btnElegirCurso.setBackground(new java.awt.Color(255, 51, 0));
        btnElegirCurso.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        btnElegirCurso.setForeground(new java.awt.Color(255, 255, 255));
        btnElegirCurso.setText("ELEGIR ");
        btnElegirCurso.setEnabled(false);
        btnElegirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirCursoActionPerformed(evt);
            }
        });
        jPanel5.add(btnElegirCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 378, -1, -1));

        btnActividadExtra.setText("ACTIVIDAD EXTRACURRICULAR");
        btnActividadExtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActividadExtraActionPerformed(evt);
            }
        });
        jPanel5.add(btnActividadExtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 420, -1, -1));

        jButton1.setText("VOLVEr");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, -1, -1));

        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.png"))); // NOI18N
        jLabel24.setText("jLabel24");
        jPanel5.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        v = new VentanaPrincipall();
        v.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdAlumnoBuscadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdAlumnoBuscadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdAlumnoBuscadoActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:
        String id;
        id = txtIdAlumnoBuscado.getText();
        int indice;
        indice=matricula.BuscarAlumno(id);
        if(indice==-1){
            JOptionPane.showMessageDialog(null,"No se encontro al alumno");
            txtAreaCursos.setEnabled(false);
            txtEleccionCurso.setEnabled(false);
            btnElegirCurso.setEnabled(false);
        }else{
            JOptionPane.showMessageDialog(null, "Se encontro al alumno");
            txtEleccionCurso.setEnabled(true);
            txtAreaCursos.setEnabled(true);
            btnElegirCurso.setEnabled(true);
            int idesito = indice;

        }
    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void txtEleccionCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEleccionCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEleccionCursoActionPerformed

    private void btnElegirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirCursoActionPerformed
        // TODO add your handling code here:
        int i;
        i = Integer.parseInt(txtEleccionCurso.getText());
        String id;
        id = txtIdAlumnoBuscado.getText();
        int indice;
        indice=matricula.BuscarAlumno(id);

        if(indice==-1){
            JOptionPane.showMessageDialog(null,"No se encontro al alumno");
            txtAreaCursos.setEnabled(false);
        }else{

            txtAreaCursos.setEnabled(true);
            if(matricula.alumnos.get(indice).cursos.size()==5){
                JOptionPane.showMessageDialog(null, "No puedes registrar mas Cursos");
                btnActividadExtra.setEnabled(true);
            }else{

                if (i == 1) {
                    Curso c = new Curso();
                    c.setNombreCurso("Matematica");
                    String[] diasMate = {"Lunes", "Martes", "Jueves"};
                    String[] horarioMate = {"7:00-9:00am", "9:00-11:00am", "9:00-11:00am"};
                    c.setDias(diasMate);
                    c.setHorario(horarioMate);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso Matematica");
                    txtEleccionCurso.setText("");
                } else if (i == 2) {
                    Curso c = new Curso();
                    c.setNombreCurso("Comunicacion");
                    String[] diasComunicacion = {"Lunes", "Miercoles"};
                    String[] horarioComunicacion = {"9:00-11:00am", "7:00-11:00am"};
                    c.setDias(diasComunicacion);
                    c.setHorario(horarioComunicacion);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso Comunicacion");
                    txtEleccionCurso.setText("");
                } else if (i == 3) {
                    Curso c = new Curso();
                    c.setNombreCurso("CTA");
                    String[] diasCta = {"Martes", "Jueves"};
                    String[] horarioCta = {"9:00-1:00pm", "11:00-1:00pm"};
                    c.setDias(diasCta);
                    c.setHorario(horarioCta);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso CTA");
                    txtEleccionCurso.setText("");
                } else if (i == 4) {
                    Curso c = new Curso();
                    c.setNombreCurso("Ingles");
                    String[] diasIngles = {"Lunes", "Lunes"};
                    String[] horarioIngles = {"11:00-1:00pm", "11:00-1:00pm"};
                    c.setDias(diasIngles);
                    c.setHorario(horarioIngles);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso Ingles");
                    txtEleccionCurso.setText("");

                }else if(i==5){
                    Curso c = new Curso();
                    c.setNombreCurso("Religion");
                    String[] diasReligion = {"Jueves", "Viernes"};
                    String[] horarioReligion = {"7:00-9:00am", "7:00-9:00am"};
                    c.setDias(diasReligion);
                    c.setHorario(horarioReligion);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso Religion");
                    txtEleccionCurso.setText("");
                }else if(i==6){
                    Curso c = new Curso();
                    c.setNombreCurso("Psicologia");
                    String[] diasPsico = {"Viernes"};
                    String[] horarioPsico = {"9:00-1:00pm"};
                    c.setDias(diasPsico);
                    c.setHorario(horarioPsico);
                    matricula.alumnos.get(indice).agregarCurso(c);
                    JOptionPane.showMessageDialog(null, "Se registro Curso Psicologia");
                    txtEleccionCurso.setText("");
                }else if(i!=1 || i!=2 || i!=3 || i!=4 || i!=5 || i!=6){
                    JOptionPane.showMessageDialog(null, "No existe el curso ASI COMO ELLA EN TU VIDA :V ");
                }

                btnActividadExtra.setEnabled(false);

            }

        }
    }//GEN-LAST:event_btnElegirCursoActionPerformed

    private void btnActividadExtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActividadExtraActionPerformed
        // TODO add your handling code here:
        ex = new VentanaExtra();
        ex.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnActividadExtraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaElegirCursosAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaElegirCursosAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaElegirCursosAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaElegirCursosAlumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaElegirCursosAlumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActividadExtra;
    public javax.swing.JButton btnBuscarAlumno;
    public javax.swing.JButton btnElegirCurso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaCursos;
    public javax.swing.JTextField txtEleccionCurso;
    public javax.swing.JTextField txtIdAlumnoBuscado;
    // End of variables declaration//GEN-END:variables
}
